# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.daily_rates:
        30000: 0.6
        50000: 0.8

    app.exchange_rates:
        EUR: 80.0
        USD: 70.0

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $dailyRates: '%app.daily_rates%'
            $exchangeRates: '%app.exchange_rates%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Explicitly configure the exchange rate provider
    App\Service\ExchangeRate\FixedExchangeRateProvider:
        arguments:
            $rates: '%app.exchange_rates%'

    # Configure the insurance calculator
    App\Service\Insurance\InsuranceCalculator:
        arguments:
            $dailyRates: '%app.daily_rates%'
